### ISSUE TITLE
pkgin upgrade and pkgin install segfault

### ISSUE THREAD

**Issue by ghost** [NetBSDfr/pkgin#94]
On a recent upgraded NetBSD amd64 system from 9.99.64 to 9.99.69 I get segfaults for `pkgin upgrade` and for some packages with `pkgin install`.

Here are the files for analysis:
* https://d.n0.is/pkgin/pkg_summary.gz
* https://d.n0.is/pkgin/pkgin_list.txt
* https://d.n0.is/pkgin/pkgin.dump.txt

irc snip
```
21:13 <nikita`> for a package which exists:
21:13 <nikita`> pkgin install python38
21:13 <nikita`> calculating dependencies...done.
21:13 <nikita`> [1]   Segmentation fault (core dumped) pkgin install python38
21:13 <nikita`> for upgrade:
21:13 <nikita`>  pkgin upgrade
21:13 <nikita`> calculating dependencies...done.
21:13 <nikita`> [1]   Segmentation fault (core dumped) pkgin upgrade
```

**Comment by teknokatze** [comment]
backtrace, without debug symbols:
```
[New process 23255]
Core was generated by `pkgin'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000077f8f2584870 in strlen () from /usr/lib/libc.so.12
(gdb) bt
#0  0x000077f8f2584870 in strlen () from /usr/lib/libc.so.12
#1  0x000077f8f24b17be in _strdup (str=0x0) at /usr/src/lib/libc/string/strdup.c:60
#2  0x000000000040db82 in xstrdup ()
#3  0x0000000000407d36 in order_install ()
#4  0x0000000000404faf in pkgin_install ()
#5  0x0000000000405ab6 in pkgin_upgrade ()
#6  0x00000000004156b1 in main ()
```
